### PR TITLE
Fix decoding optional integral (Int,Long) at the end of pretty print json.

### PR DESCRIPTION
**Pull request by russwyte**
Tests pass

Addresses #675

### CODE REVIEW

**Comment by russwyte** [comment]
I did this:
image
But the check still fails... 🤔

**Comment by russwyte** [comment]
Is there something I am missing in this PR? I am happy to add to or modify it or even create a new one.

**Review by 987Nabil — APPROVED** [review]

**Comment by 987Nabil** [comment]
@russwyte Sorry, I was a little busy recently and missed this PR. Let me know, if you need a release soonish for this

**Comment by russwyte** [comment]
Not a big rush - but as soon as practical would be great! Thank you!

**Comment by russwyte** [comment]
@987Nabil Thank you for cutting a release - but it looks like there was an issue publishing it. I don't see it in maven central.

https://mvnrepository.com/artifact/dev.zio/zio-schema

**Pull request merged**
