### PR TITLE
MessagePack codec

### PR DESCRIPTION
**Pull request by pshemass**
This is pull request that adds MessagePack codec based on `msg-pack` Java library.

### CODE REVIEW

**Comment by jdegoes** [comment]
@pshemass Excellent work. Look forward to having this one! Can you merge in the latest changes from master?

**Comment by jdegoes** [comment]
Looks fantastic! Scala 3.1.1 failed [in the CI build](https://github.com/zio/zio-schema/actions/runs/3351917277/jobs/5553691227#step:5:1807)

Can you please take a look? Try `++3.1.1` inside `sbt` locally to switch your sbt build to Scala 3.1.1

**Comment by pshemass** [comment]
> Looks fantastic! Scala 3.1.1 failed [in the CI build](https://github.com/zio/zio-schema/actions/runs/3351917277/jobs/5553691227#step:5:1807)
> 
> Can you please take a look? Try `++3.1.1` inside `sbt` locally to switch your sbt build to Scala 3.1.1

@jdegoes I rebased and used new BinaryCodec. I followed ThriftCodec. For scala 3 build failure I moved tests to `scala-2` folder because it was only test related. I hope that this is fine for the time being.

**Review by jdegoes — APPROVED** [review]

**Comment by jdegoes** [comment]
@pshemass Thanks for this wonderful contribution! Hope you get a chance to revisit the tests under Scala 3. 🙏

**Pull request merged**
