### PR TITLE
added simpleEnum annotation

### PR DESCRIPTION
**Pull request by pablf**
/claim #506
Throws exception if used where not applicable and it is added automatically if it is indeed a simple Enum.

### CODE REVIEW

**Comment by googley42** [comment]
@pablf so is the intention to automatically insert the `simpleEnum` into the derived schema? I think in the original issue I wanted to control the application of the annotation (ie make this manual process) so that users of downstream libraries like `zio-dynamodb` can choose the encoding  they want eg new projects may want the default tagged union encoding and projects that need to integrate with legacy databases say could use this new annotation.

**Comment by pablf** [comment]
And if we included an `automaticallyAdded: Boolean` in the annotation's definition? What do you think?

**Comment by pablf** [comment]
Now it should pass the tests.
@googley42 I have added automaticallyAdded. If you want to use you can use `@simpleEnum` and it will generate a `simpleEnum(false)` annotation.

**Comment by googley42** [comment]
@pablf  so I think the original intention of the issue was just to create a standard annotation for use by downstream libraries - we already have one for zio-dynamodb - but the the thought was to standardise it. The fact that the JSon codec already defaults to this behaviour probably means that there is no extra work required for derive gen macro - what do you think @jdegoes ?

**Comment by googley42** [comment]
@pablf 

> Maybe it would also be interesting for a Schema to know if it is a simple Enum, so each one of its codecs can use that information as desired, instead of checking in each codec if it is really a simple Enum

Ah yes - I get this now - this is _great_ idea and will simplify the codecs of all downstream libs!

The only thing I want to confirm is that will a manually created `@simpleEnum` override the automatically generated one? I suspect this is case and if so do you think it would be a good idea to have a unit test for this?

**Comment by pablf** [comment]
@googley42 Then great! Yes, that would be the expected behaviour. I have added the tests to ensure that it's like that in the future.

**Review by googley42 — APPROVED** [review]
LGTM and I think this a great piece of functionality - however I am not a zio-schema maintainer or have much knowledge around macros! you may want to get another review cc @zio/zio-schema

**Review by googley42 — APPROVED** [review]
.

**Review by vigoo — APPROVED** [review]

**Review by vigoo — APPROVED** [review]

**Pull request merged**
