### PR TITLE
fixed CaseClass0

### PR DESCRIPTION
**Pull request by mjabari**
issue #353

### CODE REVIEW

**Comment by jdegoes** [comment]
@mjabari Thank you! Can you insert a test for the whitespace case, e.g. `    {      }`, etc.? 

Finally, can you format the code by running scalafmt?

**Comment by jdegoes** [comment]
@mjabari can you please fix conflicts? 🙏

**Comment by mjabari** [comment]
> @mjabari Thank you! Can you insert a test for the whitespace case, e.g. ` { }`, etc.?
> 
> Finally, can you format the code by running scalafmt?

@jdegoes sorry, I dont get your point about test. anyway added a test  to decode a CaseClass0 with whitespace inside
conflict resolved!

**Comment by jdegoes** [comment]
@mjabari There have been a few changes from the hackathon, would you mind one more round of merging and I will get this promptly merged in? Thank you!

**Comment by mjabari** [comment]
done, resolved new conflicts

**Comment by jdegoes** [comment]
@vigoo How does this relate to your work?

**Comment by vigoo** [comment]
I think I also solved this in my branch. (Not only JsonCodec but others were not handling it correctly either):
https://github.com/zio/zio-schema/pull/421/files#diff-2b3004efa6280843eec4f1cc41c98f89b34df187c716a64fa73784fe78cbc9e5R509

**Pull request closed without merging**
