### PR TITLE
Publish Docs to NPM Registry

### PR DESCRIPTION
**Pull request by khajavi**
In order to be able to have integrated documents in zio.dev, we need to publish documents to the npm registry and then, fetch them in the zio.dev build process.

### CODE REVIEW

**Comment by khajavi** [comment]
I've just updated the work with the main branch.

@jdegoes @adamgfraser 
This is ready for your review.

**Comment by jdegoes** [comment]
@khajavi Is this a test or do you want this merged in? May be best to wait for `sbt-zio`?

**Comment by khajavi** [comment]
This work was the first try on integration. The `zio-sbt` project will automate most of this work.
I tested this work on my forked GitHub account and the GitHub actions work properly. We can merge it, and double-check that.
Another option is to wait, and I will add more commits to this PR which will use zio-sbt.

**Comment by jdegoes** [comment]
@khajavi Merged!

**Comment by khajavi** [comment]
Thank you!

**Pull request merged**
