### PR TITLE
Initial commit of wip from https://github.com/zio/zio-web/pull/90. #7

### PR DESCRIPTION
**Pull request by brbrown25**
>
Co-authored-by: Brandon Brown <brandon@bbrownsound.com>
Co-authored-by: Jason Pickens <jasonpickensnz@gmail.com>

### CODE REVIEW

**Comment by brbrown25** [comment]
@jdegoes this is a flattened version of the work currently in https://github.com/zio/zio-web/pull/90. I plan on working through the remaining work in the new couple of days.

**Comment by brbrown25** [comment]
I was wrapping up a zio-sql Pr and plan to look back at this one tomorrow!

**Comment by jdegoes** [comment]
@brbrown25 I think only a few changes are necessary for merging (mainly depending on ZIO JSON source, so the build will pass). If  we get this in, I don't mind doing the wrap up work myself. Any chance you can push this over the finish line?

**Comment by brbrown25** [comment]
@jdegoes most certainly I can get this build working tomorrow!

**Comment by jdegoes** [comment]
Awesome, thank you!

**Comment by brbrown25** [comment]
@jdegoes 
I tried adding the git://github.com/steinybot/zio-json.git#bug/duration-encoder branch as a build dependency and it caused 
Caused by: java.lang.ClassNotFoundException: org.scalajs.ir.ScalaJSVersions$
how ever publishing locally didn't give me any complaints. I've commented out the test and pulled in the latest main code. Unfortunately I'm not able to work any more on this at the moment but have really liked work on this and can't wait to come back for some more ZIO action!

**Comment by jdegoes** [comment]
@brbrown25 No worries, I'll take it over! Thank you for your work on this. 🙏

**Comment by jdegoes** [comment]
Closing this in favor of #28 for now.

**Pull request closed without merging**
