### PR TITLE
Add scaladoc to annotations

### PR DESCRIPTION
**Pull request by iamorozov**
This PR adds scaladoc formatted documentation to annotations in `zio.schema.annotation` package implemented in https://github.com/zio/zio-schema/issues/203

/claim #478

### CODE REVIEW

**Comment by jdegoes** [comment]
This is a great addition, however, it's not exactly what the ticket is looking for.

The ticket is looking for modifying the macros that auto-generate `Schema` (the derivation macros), and incorporating the Scaladoc attached to the user's own `case class` and `sealed trait` data types, into the `Schema` class itself, possibly as an annotation.

So, for example, if you had:

```scala
/**
 * My Scaladoc.
 */
final case class Person(name: String, age: Int)
```

Then you auto-derived `Schema[Person]` by using `DeriveSchema.gen[Person]`, then if you looked into the annotations on `Schema[Person]`, you would find one that contains the Scaladoc, including the string `My Scaladoc.`.

Does this make sense? Are you still interested in implementing this ticket?

**Comment by iamorozov** [comment]
@jdegoes Thank you for clarifying the task, it is more clear now and makes sense. I will try to make all changes needed to achieve this

**Comment by iamorozov** [comment]
@jdegoes As scaladoc is not being included into compiled classes and thus not extractable with reflection I wonder what approach should I use to add scaladoc to derived schema. Is extracting and parsing source file sounds applicable for this task?

**Comment by vigoo** [comment]
@jdegoes I think the original linked issue was really just talking about adding documentation comments in the code for the annotations (as the PR does). I would not try to parse the source code separately from the macro, if the doc comments are not provided by the compiler.

**Comment by jdegoes** [comment]
@vigoo All right, happy to go with your interpretation (it's less work, anyway).

I had assumed that Scaladoc would be visible at compile-time to macros and not require source parsing.

**Review by vigoo — APPROVED** [review]

**Pull request merged**
