### PR TITLE
add regex phone number validation for Serbia

### PR DESCRIPTION
**Pull request by subotic**
Towards #251

### CODE REVIEW

**Comment by jdegoes** [comment]
@subotic Thanks for your work on this! Can you resolve conflicts?

**Comment by jdegoes** [comment]
Thank you for your work on this!

Good to merge when the conflicts are resolved and the build is passing! Be sure to format your code using `scalafmt` commands in the console.

**Comment by subotic** [comment]
@jdegoes I decided to ignore spaces after checking for the right prefix. I don't know if this is how it should be done. Input is appreciated.

**Comment by subotic** [comment]
@jdegoes this should be ready for merging

**Review by jdegoes — APPROVED** [review]

**Review by jdegoes — APPROVED** [review]

**Comment by jdegoes** [comment]
One minor conflict, then good to merge!

**Comment by subotic** [comment]
closing, because nothing left to merge ...

**Pull request closed without merging**
