### PR TITLE
added case for SetValue

### PR DESCRIPTION
**Pull request by mjabari**
Cannot serialize DynamicValue.SetValue #330

### CODE REVIEW

**Comment by vigoo** [comment]
Hi, could you rebase it on https://github.com/zio/zio-schema/pull/331 so we see if it fixed my tests?

**Comment by mjabari** [comment]
> Hi, could you rebase it on #331 so we see if it fixed my tests?

done

**Review by vigoo — APPROVED** [review]
Nice, thank you! Ready for merge if you could sign the CLA

**Comment by mjabari** [comment]
I signed the CLA but I don't know why it's still not signed!

**Pull request merged**
