### PR TITLE
Implement reified optics with AccessorBuilder and type-safe generic r…

### PR DESCRIPTION
**Pull request by thinkharderdev**
…ecord/enum enodings

### CODE REVIEW

**Comment by thinkharderdev** [comment]
@jdegoes I think this guy is ready. I want to create a more comprehensive example for an AccessorBuilder to serve as a code example for users and to provide a better test base for the specs but will do that in a separate PR to not hold this one up.

**Review by jdegoes — APPROVED** [review]

**Review by jdegoes — DISMISSED** [review]
Excellent work! With a PR of this scope, I think it's best to get this in now, and we can do some fixups / polishing later.

Thank you for your work on this!

**Comment by jdegoes** [comment]
@thinkharderdev I think I'd just get the tests passing and then I can review / approve.

**Comment by thinkharderdev** [comment]
> @thinkharderdev I think I'd just get the tests passing and then I can review / approve.

Yep, it looks like the recent UUID PR is causing a weird issue with the Gen performance. Not quite sure yet but working on debugging it.

**Comment by jdegoes** [comment]
> I want to create a more comprehensive example for an AccessorBuilder to serve as a code example for users and to provide a better test base for the specs but will do that in a separate PR to not hold this one up.

It occurred to me we could have a `zio-schema-optics` module in this project, which uses reified optics combined with dynamic value to produce lenses / prisms / traversals for records & enums. Such an example could, even if just a "toy", help flesh out the API and get library authors started.

This work should immediately benefit:

 - ZIO SQL (`select(Person.name ++ Person.age).from(table).where(Person.age > 20)`
 - ZIO DynamoDB (`DynamoDBQuery.scanSome(table).where(Person.age > 20)`
 - ZIO Flow (`remotePerson.get(Person.age)`)

Plus other ones (e.g. ZIO Aeorspike) not quite as far along.

**Comment by thinkharderdev** [comment]
> (Usually Gen performance issues are caused by filtering on the Gen.)

Ok sorted it out. Tests are passing now.

**Review by jdegoes — APPROVED** [review]

**Pull request merged**
