### PR TITLE
test for Map JSON encoder/decoder

### LINKED ISSUE #447: Encoding Decoding Map to JSON
How to reproduce, create a case class with an optional field of type Map:
```scala
case class ServerVersion(
    server: String,
    license: String,
    version: String,
    details: Map[String, String] = Map.empty
)

given Schema[ServerVersion] = DeriveSchema.gen[ServerVersion]
```

Expected test to pass:
```scala

      test("Encode/Decode ServerInfo from json using schema") {
        for
          _ <- ZIO.unit
          json = """{ "server": "arango", "license": "community", "version": "3.10.1"}"""
          chunks = Chunk.fromArray(json.getBytes)
          serverInfo <- ZIO.fromEither(
            JsonCodec.decode[ServerVersion](given_Schema_ServerVersion)(chunks)
          )
        yield assertTrue(
          serverInfo == ServerVersion("arango", "community", "3.10.1")
        )
      }
```

Error: the field details is decoded as `Map("" -> "" )`   instead of `Map.empty`:
image

I tried also with next annotations:
```scala
import zio.schema.annotation.{fieldDefaultValue, optionalField}

case class ServerVersion(
    server: String,
    license: String,
    version: String,
    @optionalField
    @fieldDefaultValue[Map[String, String]](Map.empty)
    details: Map[String, String] = Map.empty
)
```

### PR DESCRIPTION
**Pull request by carlos-verdes**
So far I just created tests to reproduce the errors (check issue #447 for more details).
If we agree on this spec I can try to fix the code, I may appreciate some guidance though

Fixes #447

### CODE REVIEW

**Comment by jdegoes** [comment]
@carlos-verdes I think, yes, maps of `String` to some other type should always be encoded/decoded as JSON objects.

For other key types, of course, we can use a different JSON encoding.

**Comment by jdegoes** [comment]
@carlos-verdes Can you please look at the build failures when you get a chance? Thank you!

**Comment by jdegoes** [comment]
@carlos-verdes Please re-open if you get a chance to fix the CI failures. Thanks for your work on this!

**Comment by carlos-verdes** [comment]
Hi @jdegoes as I mentioned I didn't want to start the code before we agree with the change so I only submitted the tests to reproduce the expected behavior (which obviously fails).

I would appreciate some guidance into which files to look first and I'm willing to post some code

**Pull request closed without merging**
